sudo: required
services:
  - docker

before_install:
  - docker build -t acteck19/react-test -f ./client/Dockerfile.dev ./client



script:
  - docker run acteck19/react-test npm test -- --coverage

after_success:
  - docker build -t acteck19/multi-client ./cleint 
  - docker build -t acteck19/multi-nginx ./nginx
  - docker build -t acteck19/multi-server ./server
  - docker build -t acteck19/multi-worker ./worker
  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin



  # take those images and push them to docker hub
  - docker push acteck19/multi-client 
  - docker push acteck19/multi-server
  - docker push acteck19/multi-nginx 
  - docker push acteck19/multi-worker 


